// Mock data for videos
export const videos = [
  {
    id: "1",
    title: "Amazing Web Development Techniques for 2025",
    description: "Learn the latest web development techniques that will revolutionize how you build applications.",
    date: "May 15, 2025",
    category: "Development",
    views: 12453,
    likes: 1243,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "2",
    title: "Mastering CSS Grid Layout",
    description: "A comprehensive guide to using CSS Grid for modern web layouts.",
    date: "May 10, 2025",
    category: "CSS",
    views: 8765,
    likes: 932,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "3",
    title: "React Server Components Explained",
    description: "Understanding the benefits and implementation of React Server Components.",
    date: "May 5, 2025",
    category: "React",
    views: 9876,
    likes: 876,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "4",
    title: "Building Accessible Web Forms",
    description: "Learn how to create forms that are accessible to all users.",
    date: "April 28, 2025",
    category: "Accessibility",
    views: 6543,
    likes: 543,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "5",
    title: "JavaScript Performance Optimization",
    description: "Techniques to make your JavaScript code run faster and more efficiently.",
    date: "April 20, 2025",
    category: "JavaScript",
    views: 7654,
    likes: 654,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
  {
    id: "6",
    title: "Introduction to Web Animation APIs",
    description: "Explore the various APIs available for creating web animations.",
    date: "April 15, 2025",
    category: "Animation",
    views: 5432,
    likes: 432,
    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
]